[project]
name = "graiax-silkcoder"
version = "0.4.0a0" # WIP
description = "transform audio file from/to silk"
keywords = ["silkv3"]
authors = [
    {name = "I Love Study", email = "1450069615@qq.com"},
]
dependencies = [
    "typing-extensions >= 4.10.0; python_version < '3.13'",
    "aiologic >= 0.14.0"
]
readme = "README.md"
requires-python = ">=3.10, <4.0"
license = {text = "BSD-3-Clause"}

[project.optional-dependencies]
# python-soxr 在 0.5 后性能大幅提升
# soundfile 0.13.0 支持 compression_level
libsndfile = ["soundfile >= 0.13.0", "soxr >= 0.5.0"]
ffmpeg = ["imageio-ffmpeg >= 0.5.0"]

[project.urls]
repository = "https://github.com/I-love-study/graiax-silkcoder"


[tool.pdm.dev-dependencies]
# librosa 0.11.0 有 numpy 2.0 支持
test = [
    "aiofile",
    "librosa>=0.11.0rc1",
    "pytest",
    "pytest-sugar",
    "pytest-asyncio",
    "pytest-xdist",
]

[tool.pytest.ini_options]
addopts = "-ra -q -m 'not fast'"
filterwarnings = [
    "ignore:'audioop' is deprecated:DeprecationWarning",
    "ignore:.*librosa.*:UserWarning",
    "ignore:.*librosa.*:FutureWarning",
    "ignore::DeprecationWarning:audioread.rawread"
]
minversion = "8.0"
tmp_path_retention_count = 1
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "class"
markers = [
    "fast: marks tests as fast"
]

[tool.cibuildwheel]
# 别用 32 位了朋友们
skip = "*_i686 *-win32"
enable = ["cpython-freethreading"]
test-requires = "pytest"
test-command = "pytest -m fast"

[tool.cibuildwheel.windows]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.meson-python]
limited-api = true
allow-windows-internal-shared-libs = true

[tool.meson-python.args]
setup = ['--vsenv']

[build-system]
#meson-python >= 0.18.0
requires = ["meson-python@git+https://github.com/mesonbuild/meson-python.git@main", "cffi"]
build-backend = "mesonpy"
