[tool.poetry]
name = "graiax-silkcoder"
version = "0.1.1"
description = "transform audio file to silk"
authors = ["I_love_study <1450069615@qq.com>"]
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://github.com/I-love-study/graiax-silkcoder"
repository = "https://github.com/I-love-study/graiax-silkcoder"

packages = [
    {include = "graiax", from = "src"},
]

include = [
    {path = "src/c_silkv3/src/*", format = "sdist"},
    {path = "src/c_silkv3/interface/*", format = "sdist"}
]

build = "build.py"

[tool.poetry.dependencies]
#仅在python3.8+测试过，强烈建议赶紧用上Python3.8+
python = "^3.6"
imageio-ffmpeg = { version = "*", optional = true }

[tool.poetry.extras]
ffmpeg = ["imageio-ffmpeg"]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"