[project]
name = "graiax-silkcoder"
version = "0.4.0a0" # WIP
description = "transform audio file to silk"
keywords = ["silkv3"]
authors = [
    {name = "I Love Study", email = "1450069615@qq.com"},
]
dependencies = [
    "typing-extensions >= 4.10.0; python_version < '3.13'",
    "aiologic >= 0.14.0"
]
readme = "README.md"
requires-python = ">=3.10, <3.14"
license = {text = "BSD-3-Clause"}

[project.optional-dependencies]
# python-soxr 在 0.5 后性能大幅提升
# soundfile 0.13.0 支持 compression_level
libsndfile = ["soundfile >= 0.13.0", "soxr >= 0.5.0"]
ffmpeg = ["imageio-ffmpeg >= 0.5.0"]

[project.urls]
repository = "https://github.com/I-love-study/graiax-silkcoder"

[tool.pdm.build]
package-dir = "src"
includes = ["src/graiax"]  
source-includes = ["src/c_silkv3"]
distribution = true
custom-hook = "build.py"
run-setuptools = true

[tool.pdm.dev-dependencies]
# librosa 0.11.0 有 numpy 2.0 支持
test = [
  "aiofile",
  "librosa>=0.11.0rc0",
  "pytest",
  "pytest-sugar",
  "pytest-asyncio",
]

[tool.pytest.ini_options]
addopts = "-ra -q"
filterwarnings = ["ignore:'audioop' is deprecated:DeprecationWarning"]
minversion = "8.0"
testpaths = ["tests"]

[tool.cibuildwheel]
skip = "*-musllinux_* *_i686 *-win32"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[build-system]
requires = ["pdm-backend", "setuptools", "cffi"]
build-backend = "pdm.backend"
