name: Build & Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.1
      
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
      
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: 3.10
          architecture: x64
      
      - name: Build SDist
        run: |
          pdm build --no-wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
      
  upload_all:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          verbose: true